version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
      day: "sunday"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
      day: "sunday"
