name: Lint and Unit Tests

on:
  pull_request: {}
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-24.04  # using python 3.12
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)  # see: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-output-parameter-set-output
      id: nvm
    - name: Set up node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - name: Cache npm
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Cache pip
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: npm ci
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup pipenv
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Fetch Dependent Files (content repo)
      run: |
        cd content-repo
        wget https://raw.githubusercontent.com/demisto/content/master/Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
        wget https://raw.githubusercontent.com/demisto/content/master/Tests/demistomock/demistomock.py
        sed -i -e '/from DemistoClassApiModule import */d' CommonServerPython.py
    - name: Lint
      run: |
        cd content-repo
        pipenv run mypy
        pipenv run flake8 *.py
    - name: Unit Testing
      run: |
        cd content-repo
        pipenv run pytest -v
