name: Deploy Preview

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Build deploy preview
        id: deploy-netlify
        run: |
          sudo yarn global add netlify-cli
          echo ::set-env name=NETLIFY_OUTPUT::$(netlify deploy --dir=build)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Set Netlify URL envars
        id: netlify-envars
        run: |
          NETLIFY_URL=$(echo ${{ env.NETLIFY_OUTPUT }} | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*(--)[a-zA-Z0-9./?=_-]*')
          NETLIFY_LOGS_URL=$(echo ${{ env.NETLIFY_OUTPUT }} | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*')
          echo "::set-output name=NETLIFY_URL::$NETLIFY_URL"
          echo "::set-output name=NETLIFY_LOGS_URL::$NETLIFY_LOGS_URL"
      - name: Comment deploy preview URLs
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: "This pull request is being automatically deployed to Netlify.\n\n🔍 Inspect: ${{ steps.netlify-envars.outputs.NETLIFY_LOGS_URL }}\n✅ Preview: ${{ steps.netlify-envars.outputs.NETLIFY_URL }}"
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false
