variables:
  CURRENT_BRANCH_NAME: remove-firebase-authenticate

include:
  - file: "/.gitlab/ci/content-docs/.gitlab-ci.yml"
    ref: remove-firebase-authenticate
    project: "${CI_PROJECT_NAMESPACE}/infra"


