variables:
  CURRENT_BRANCH_NAME: "test-sysctl-vm_max_map_count"

include:
  - file: "/.gitlab/ci/content-docs/.gitlab-ci.yml"
    ref: "test-sysctl-vm_max_map_count"
    project: "${CI_PROJECT_NAMESPACE}/infra"
