variables:
  CURRENT_BRANCH_NAME: sk_content_docs_update_docker

include:
  - file: "/.gitlab/ci/content-docs/.gitlab-ci.yml"
    ref: sk_content_docs_update_docker
    project: "${CI_PROJECT_NAMESPACE}/infra"
